### ISSUE TITLE
Could you add a LICENSE file?

### ISSUE THREAD

**Issue by hnakamur** [otm/blade#1]
First of all, thanks for creating and sharing a nice software!

Could you add a LICENSE file?
[Choosing an OSS license doesn’t need to be scary - ChooseALicense.com](http://choosealicense.com/) maybe helpful when you choose a license.
I hope you choose a permissive licenses like MIT and Apache.
Thanks!

**Comment by otm** [comment]
8b924a08735bedf7bc866cc58afa9459d754aecf Added licensen file

**Comment by hnakamur** [comment]
Thanks!
